service: proy2

plugins:
  - serverless-offline

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-west-2

functions:
  encrypt:
    handler: handler.encrypt
    events:
      - httpApi:
          path: /encrypt/{mensaje}
          method: get
  decrypt:
    handler: handler.decrypt
    events:
      - httpApi:
          path: /decrypt/{mensaje}/{key}
          method: get
